sudo: true
language: android
jdk: oraclejdk8

before_install:
 - chmod +x gradlew
 - source setupArtifactoryCredentialsForCircleCI.sh && copyEnvVarsToGradleProperties

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository